engineStrict: true
verifyDepsBeforeRun: error
minimumReleaseAgeExclude:
  - '@antfu/eslint-config@9.2.0'
  - miniflare@4.20260721.0
  - wrangler@4.113.0
shamefullyHoist: true
shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off
patchedDependencies:
  '@scryfall/api-types@1.0.0-alpha.4': patches/@scryfall__api-types@1.0.0-alpha.4.patch
  vite-plugin-checker@0.14.4: patches/vite-plugin-checker@0.14.4.patch
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
