export const STILL_IMAGE_COMPATIBILITY_PROFILE = 'still-image-v1' as const;
export const MAX_STILL_IMAGE_INGESTION_BYTES = 25 * 1024 * 1024;
export const MAX_STILL_IMAGE_AXIS = 8192;
export const MAX_STILL_IMAGE_PIXELS = 16_777_216;
export const STILL_IMAGE_THUMBNAIL_MAX_WIDTH = 640;
export const STILL_IMAGE_THUMBNAIL_MAX_HEIGHT = 360;
