/**
 * Graphics Asset Library reconciliation contract.
 *
 * D1 is authoritative for which Graphic Asset Content the library expects to
 * reach. The canonical byte store is authoritative only for the bytes it
 * currently holds. Reconciliation compares the two, records what it finds, and
 * never creates catalogue state from a byte observation.
 *
 * `graphic_asset_contents.availability` is advisory reconciliation state, not a
 * reader authority. A reader that needs bytes always asks the byte store,
 * because D1 can still say `available` between a byte loss and the next sweep,
 * and `unavailable` after the bytes came back. The flag exists so an incident
 * stays visible, alertable, and repairable between sweeps; reconciliation is
 * its only writer, and every reader that observes a disagreement feeds it.
 */

/** The policy actor recorded against every automated reconciliation decision. */
export const GRAPHICS_RECONCILIATION_ACTOR = 'graphics-reconciliation-policy';

/** How many candidates one sweep processes per reconciliation stage. */
export const GRAPHICS_RECONCILIATION_STAGE_BATCH = 200;

/**
 * How long one administrator repair or regeneration may hold its staged working
 * copy. A crashed action leaves the claim behind; after this lease a sweep
 * reclaims the staged bytes rather than leaking them.
 */
export const GRAPHICS_WORKING_COPY_LEASE_MILLISECONDS = 60 * 60 * 1000;

/**
 * The kinds of disagreement reconciliation records.
 *
 * `critical-integrity-incident` is always isolated: it fails closed and is
 * never repaired by overwriting bytes or mutating object metadata.
 */
export const GRAPHICS_DISCREPANCY_KINDS = [
	'unavailable-content',
	'missing-derivative',
	'unexpected-object',
	'critical-integrity-incident',
] as const;

export const GRAPHICS_DISCREPANCY_STATES = ['open', 'resolved'] as const;

/** Why a discrepancy was opened. Stable codes; administrators see these. */
export const GRAPHICS_DISCREPANCY_REASON_CODES = [
	/** The catalogue expects these bytes and the canonical store does not hold them. */
	'canonical-object-missing',
	/** The object exists but its size or media type contradicts the catalogue. */
	'canonical-object-facts-mismatch',
	/** The object is missing or contradicts the redundant digest metadata it was written with. */
	'canonical-object-redundant-metadata-mismatch',
	/** Verified bytes hash to something other than the digest that owns their key. */
	'canonical-object-digest-mismatch',
	/** An object in the canonical store whose key is not a digest-owned identity. */
	'foreign-canonical-object',
	/** A Graphics Derivative's generated bytes are missing from the canonical store. */
	'derivative-object-missing',
	/** Regeneration produced bytes other than the recorded deterministic result. */
	'derivative-regeneration-mismatch',
	/** Bytes present in the canonical store that the catalogue does not expect. */
	'unexpected-canonical-object',
	/** Content became reachable again while its quarantined bytes were being deleted. */
	'quarantine-deletion-conflict',
] as const;

/** How a discrepancy ended. Every one is an observation, never an assumption. */
export const GRAPHICS_DISCREPANCY_RESOLUTIONS = [
	'byte-store-agrees',
	'repaired-with-exact-bytes',
	'restored-from-quarantine',
	'derivative-regenerated',
	'content-no-longer-expected',
	'object-deleted-after-recheck',
] as const;

/**
 * The actions an administrator may take in a given state. An isolated critical
 * integrity incident offers only `recheck`: repair by overwrite or metadata
 * mutation is not an available action at all.
 */
export const GRAPHICS_DISCREPANCY_ACTIONS = [
	/** Re-observe what a listing and a head request can see. */
	'recheck',
	/**
	 * Re-read and re-hash the stored bytes in full against the complete
	 * expectation. This is the only action valid on an isolated critical
	 * integrity incident, because it is the only one that can settle one without
	 * writing, and the only way to detect bytes that changed behind metadata
	 * that still agrees. Verified bytes held under a Content Quarantine record
	 * are restored by releasing that record.
	 */
	'verify-stored-bytes',
	'repair-with-exact-bytes',
	'regenerate-derivative',
] as const;

/** Why an attempted repair, restoration, or regeneration was refused. */
export const GRAPHICS_REPAIR_REJECTION_CODES = [
	'action-not-valid-in-state',
	'discrepancy-already-resolved',
	'digest-mismatch',
	'byte-length-mismatch',
	'canonical-mime-mismatch',
	'validation-facts-mismatch',
	'source-content-unavailable',
	'stored-bytes-missing',
	'derivative-regeneration-unavailable',
	'byte-store-unavailable',
	'integrity-incident-isolated',
] as const;

export const GRAPHICS_RECONCILIATION_EVIDENCE_CATEGORIES = [
	'content-unavailable-detected',
	'content-availability-restored',
	'content-repaired',
	'content-restored-from-quarantine',
	'derivative-missing-detected',
	'derivative-regenerated',
	'unexpected-object-quarantined',
	'critical-integrity-incident',
	'discrepancy-rechecked',
	'repair-rejected',
] as const;

/**
 * The canonical object identity is the application digest under a fixed prefix.
 * Anything else in the canonical store is foreign, never adopted, and never
 * deleted automatically.
 */
export const GRAPHICS_CANONICAL_OBJECT_PREFIX = 'sha256/';

const CANONICAL_OBJECT_KEY_PATTERN = /^sha256\/[a-f0-9]{64}$/;

export function canonicalObjectDigest(key: string): string | undefined {
	return CANONICAL_OBJECT_KEY_PATTERN.test(key)
		? key.slice(GRAPHICS_CANONICAL_OBJECT_PREFIX.length)
		: undefined;
}
