export const pointsList = new Map<string, number>([
  ['Tamiyo, Inquisitive Student', 1],
  ['Nethergoyf', 1],
  ['Planar Nexus', 1],
  ['Abhorrent Oculus', 1],
  ['Ancient Tomb', 1],
  ['Balance', 1],
  ['Broadside Bombardiers', 1],
  ['Caves of Chaos Adventurer', 1],
  ['Comet, Stellar Pup', 1],
  ['Crop Rotation', 1],
  ['Deathrite Shaman', 1],
  ['Demonic Counsel', 1],
  ['Dreadhorde Arcanist', 1],
  ['Enlightened Tutor', 1],
  ['Fable of the Mirror - Breaker', 1],
  ['Force of Will', 1],
  ['Forth Eorlingas!', 1],
  ['Gamble', 1],
  ['Gifts Ungiven', 1],
  ['Goblin Recruiter', 1],
  ['Intuition', 1],
  ['Karakas', 1],
  ['Library of Alexandria', 1],
  ['Mana Drain', 1],
  ['Mana Vault', 1],
  ['Merchant Scroll', 1],
  ['Mind Twist', 1],
  ['Mishra\'s Workshop', 1],
  ['Murktide Regent', 1],
  ['Mystical Tutor', 1],
  ['Oath of Druids', 1],
  ['Orcish Bowmasters', 1],
  ['Phlage, Titan of Fire\'s Fury', 1],
  ['Profane Tutor', 1],
  ['Psychic Frog', 1],
  ['Reanimate', 1],
  ['Seasoned Dungeoneer', 1],
  ['Sensei\'s Divining Top', 1],
  ['Skullclamp', 1],
  ['Snapcaster Mage', 1],
  ['Spellseeker', 1],
  ['Strip Mine', 1],
  ['Tainted Pact', 1],
  ['The One Ring', 1],
  ['Timetwister', 1],
  ['Tinker', 1],
  ['True - Name Nemesis', 1],
  ['Undermountain Adventurer', 1],
  ['Urza\'s Saga', 1],
  ['Wasteland', 1],
  ['Wishclaw Talisman', 1],
  ['Channel', 2],
  ['Demonic Tutor', 2],
  ['Dig Through Time', 1],
  ['Gush', 2],
  ['Imperial Seal', 2],
  ['Minsc & Boo, Timeless Heroes', 2],
  ['Nadu, Winged Wisdom', 2],
  ['Oko, Thief of Crowns', 1],
  ['Ragavan, Nimble Pilferer', 1],
  ['Tolarian Academy', 2],
  ['Treasure Cruise', 2],
  ['Uro, Titan of Nature\'s Wrath', 2],
  ['Wrenn and Six', 2],
  ['Flash', 3],
  ['Lutri, the Spellchaser', 3],
  ['Lurrus of the Dream-Den', 3],
  ['Mox Emerald', 3],
  ['Mox Jet', 3],
  ['Mox Pearl', 3],
  ['Mox Ruby', 3],
  ['Mox Sapphire', 3],
  ['Sol Ring', 3],
  ['Underworld Breach', 3],
  ['Vampiric Tutor', 3],
  ['White Plume Adventurer', 3],
  ['Black Lotus', 4],
  ['Thassa\'s Oracle', 4],
  ['Time Vault', 4],
  ['Ancestral Recall', 5],
  ['Mana Crypt', 5],
  ['Time Walk', 5],
])
