import type {
	BroadcastDeckListCardResolutionRequest,
	BroadcastDeckListCardResolver,
	ResolvedBroadcastDeckListCard,
} from '~~/server/modules/broadcast-deck-list-import';
import { describe, expect, it, vi } from 'vitest';
import { importBroadcastDeckList } from '~~/server/modules/broadcast-deck-list-import';

function resolvedCard(
	request: BroadcastDeckListCardResolutionRequest,
	overrides: Partial<ResolvedBroadcastDeckListCard> = {},
): ResolvedBroadcastDeckListCard {
	return {
		canonicalName: request.name,
		scryfallId: `${request.name}-${request.setCode ?? 'default'}-${request.collectorNumber ?? 'default'}`,
		oracleId: `${request.name}-oracle`,
		setCode: request.setCode ?? 'dft',
		collectorNumber: request.collectorNumber ?? '1',
		cardType: 'Instant',
		colors: 'R',
		manaCost: '{R}',
		manaValue: 1,
		deckCounterTypes: [],
		...overrides,
	};
}

function resolvingAllCards(): BroadcastDeckListCardResolver {
	return {
		resolve: vi.fn(async (requests: readonly BroadcastDeckListCardResolutionRequest[]) => requests.map(request => ({
			status: 'resolved' as const,
			card: resolvedCard(request),
		}))),
	};
}

describe('broadcast Deck List import', () => {
	it('normalizes pasted text and accepts the three settled quantity forms', async () => {
		const resolver = resolvingAllCards();
		const result = await importBroadcastDeckList(
			'\uFEFF  04 Lightning Bolt\r\n\r\n2x Shock\r 1X Mountain  ',
			resolver,
		);

		expect(result).toEqual({
			ok: true,
			document: {
				sourceText: '04 Lightning Bolt\n2x Shock\n1X Mountain',
				mainboard: [
					expect.objectContaining({ canonicalName: 'Lightning Bolt', quantity: 4, sortOrder: 0 }),
					expect.objectContaining({ canonicalName: 'Shock', quantity: 2, sortOrder: 1 }),
					expect.objectContaining({ canonicalName: 'Mountain', quantity: 1, sortOrder: 2 }),
				],
				sideboard: [],
				companion: null,
			},
		});
	});

	it('uses exact case-insensitive headings and defaults rows before a heading to Mainboard', async () => {
		const result = await importBroadcastDeckList([
			'1 Llanowar Elves',
			'sIdEbOaRd',
			'2 Duress',
			'Deck',
			'3 Forest',
			'COMPANION',
			'1 Jegantha, the Wellspring',
		].join('\n'), resolvingAllCards());

		expect(result.ok).toBe(true);
		if (!result.ok)
			return;
		expect(result.document.mainboard.map(entry => [entry.canonicalName, entry.quantity, entry.sortOrder])).toEqual([
			['Llanowar Elves', 1, 0],
			['Forest', 3, 1],
		]);
		expect(result.document.sideboard.map(entry => [entry.canonicalName, entry.quantity, entry.sortOrder])).toEqual([
			['Duress', 2, 0],
		]);
		expect(result.document.companion).toEqual(expect.objectContaining({
			canonicalName: 'Jegantha, the Wellspring',
			quantity: 1,
			sortOrder: 0,
		}));
	});

	it('parses terminal set and collector printing hints without changing card names', async () => {
		const resolver = resolvingAllCards();
		const result = await importBroadcastDeckList([
			'1 Lightning Bolt (2XM)',
			'1 Lightning Bolt (sld) 101',
			'1 Who // What // When // Where // Why',
		].join('\n'), resolver);

		expect(result.ok).toBe(true);
		expect(resolver.resolve).toHaveBeenCalledWith([
			{ name: 'Lightning Bolt', setCode: '2xm', collectorNumber: null },
			{ name: 'Lightning Bolt', setCode: 'sld', collectorNumber: '101' },
			{ name: 'Who // What // When // Where // Why', setCode: null, collectorNumber: null },
		]);
	});

	it('returns every stable syntax error instead of ignoring unsupported export decorations', async () => {
		const result = await importBroadcastDeckList([
			'Commander',
			'4 x Lightning Bolt',
			'0 Shock',
			'1.5 Island',
			'-1 Swamp',
			'1 Lightning Bolt *F*',
			'# generated by a deck site',
			'Name My Favourite Deck',
			'Creatures',
			'1 Lightning Bolt (M21) 123 foil',
			'1 Shock # Burn',
		].join('\n'), resolvingAllCards());

		expect(result).toEqual({
			ok: false,
			errors: [
				expect.objectContaining({ lineNumber: 1, code: 'UNSUPPORTED_SECTION', sourceText: 'Commander' }),
				expect.objectContaining({ lineNumber: 2, code: 'INVALID_QUANTITY', sourceText: '4 x Lightning Bolt' }),
				expect.objectContaining({ lineNumber: 3, code: 'INVALID_QUANTITY', sourceText: '0 Shock' }),
				expect.objectContaining({ lineNumber: 4, code: 'INVALID_QUANTITY', sourceText: '1.5 Island' }),
				expect.objectContaining({ lineNumber: 5, code: 'INVALID_QUANTITY', sourceText: '-1 Swamp' }),
				expect.objectContaining({ lineNumber: 6, code: 'UNSUPPORTED_SYNTAX', sourceText: '1 Lightning Bolt *F*' }),
				expect.objectContaining({ lineNumber: 7, code: 'UNSUPPORTED_SYNTAX', sourceText: '# generated by a deck site' }),
				expect.objectContaining({ lineNumber: 8, code: 'UNSUPPORTED_SYNTAX', sourceText: 'Name My Favourite Deck' }),
				expect.objectContaining({ lineNumber: 9, code: 'UNSUPPORTED_SECTION', sourceText: 'Creatures' }),
				expect.objectContaining({ lineNumber: 10, code: 'UNSUPPORTED_SYNTAX', sourceText: '1 Lightning Bolt (M21) 123 foil' }),
				expect.objectContaining({ lineNumber: 11, code: 'UNSUPPORTED_SYNTAX', sourceText: '1 Shock # Burn' }),
			],
		});
	});

	it('rejects every researched decoration family even when a resolver would accept the decorated name', async () => {
		const result = await importBroadcastDeckList([
			'1 Lightning Bolt *S*',
			'1 Lightning Bolt *A*',
			'1 Lightning Bolt *IT*',
			'1 Lightning Bolt *F:pre*',
			'1 Lightning Bolt `Burn`',
			'1 Lightning Bolt (ATQ:1074)',
		].join('\n'), resolvingAllCards());

		expect(result.ok).toBe(false);
		if (result.ok)
			return;
		expect(result.errors).toHaveLength(6);
		expect(result.errors).toEqual([
			expect.objectContaining({ lineNumber: 1, code: 'UNSUPPORTED_SYNTAX' }),
			expect.objectContaining({ lineNumber: 2, code: 'UNSUPPORTED_SYNTAX' }),
			expect.objectContaining({ lineNumber: 3, code: 'UNSUPPORTED_SYNTAX' }),
			expect.objectContaining({ lineNumber: 4, code: 'UNSUPPORTED_SYNTAX' }),
			expect.objectContaining({ lineNumber: 5, code: 'UNSUPPORTED_SYNTAX' }),
			expect.objectContaining({ lineNumber: 6, code: 'UNSUPPORTED_SYNTAX' }),
		]);
	});

	it('requires an ASCII space between quantity and card name', async () => {
		const result = await importBroadcastDeckList('4\tLightning Bolt', resolvingAllCards());

		expect(result).toEqual({
			ok: false,
			errors: [expect.objectContaining({ lineNumber: 1, code: 'INVALID_QUANTITY' })],
		});
	});

	it('requires one quantity-one Companion row and reports every Companion error', async () => {
		const result = await importBroadcastDeckList([
			'1 Forest',
			'Companion',
			'2 Jegantha, the Wellspring',
			'1 Lurrus of the Dream-Den',
		].join('\n'), resolvingAllCards());

		expect(result).toEqual({
			ok: false,
			errors: [
				expect.objectContaining({ lineNumber: 3, code: 'INVALID_COMPANION_QUANTITY' }),
				expect.objectContaining({ lineNumber: 4, code: 'MULTIPLE_COMPANIONS' }),
			],
		});
	});

	it('refuses oversized UTF-8 sources and physical-line counts before card resolution', async () => {
		const resolver = resolvingAllCards();
		const sourceTooLarge = await importBroadcastDeckList(`1 ${'é'.repeat(32_768)}`, resolver);
		const tooManyLines = await importBroadcastDeckList(Array.from({ length: 501 }).fill('').join('\n'), resolver);

		expect(sourceTooLarge).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'SOURCE_TOO_LARGE' })],
		});
		expect(tooManyLines).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'TOO_MANY_LINES' })],
		});
		expect(resolver.resolve).not.toHaveBeenCalled();
	});

	it('accepts each exact safety boundary', async () => {
		const sourceAtLimit = await importBroadcastDeckList(`1 ${'a'.repeat(65_534)}`, resolvingAllCards());
		const linesAtLimit = await importBroadcastDeckList(
			[...Array.from({ length: 499 }).fill(''), '1 Forest'].join('\n'),
			resolvingAllCards(),
		);
		const rowsAtLimit = await importBroadcastDeckList(
			Array.from({ length: 250 }, (_, index) => `1 Card ${index}`).join('\n'),
			resolvingAllCards(),
		);
		const mergedAtLimit = await importBroadcastDeckList(
			'600 Lightning Bolt (SLD) 1\n399 Lightning Bolt (SLD) 1',
			resolvingAllCards(),
		);

		expect(sourceAtLimit.ok).toBe(true);
		expect(linesAtLimit.ok).toBe(true);
		expect(rowsAtLimit.ok).toBe(true);
		expect(mergedAtLimit).toEqual({
			ok: true,
			document: expect.objectContaining({
				mainboard: [expect.objectContaining({ quantity: 999 })],
			}),
		});
	});

	it('refuses more than 250 parsed card rows before card resolution', async () => {
		const resolver = resolvingAllCards();
		const source = Array.from({ length: 251 }, (_, index) => `1 Card ${index}`).join('\n');

		const result = await importBroadcastDeckList(source, resolver);

		expect(result).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'TOO_MANY_CARD_ROWS' })],
		});
		expect(resolver.resolve).not.toHaveBeenCalled();
	});

	it('accepts total quantity 2,000 and refuses 2,001 before card resolution', async () => {
		const accepted = await importBroadcastDeckList('999 Alpha\n999 Beta\n2 Gamma', resolvingAllCards());
		const refusingResolver = resolvingAllCards();
		const refused = await importBroadcastDeckList('999 Alpha\n999 Beta\n3 Gamma', refusingResolver);

		expect(accepted.ok).toBe(true);
		expect(refused).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'TOTAL_QUANTITY_EXCEEDED' })],
		});
		expect(refusingResolver.resolve).not.toHaveBeenCalled();
	});

	it('accepts a Sideboard-only list while refusing empty and Companion-only pastes', async () => {
		const empty = await importBroadcastDeckList('\n Mainboard \n', resolvingAllCards());
		const companionOnly = await importBroadcastDeckList('Companion\n1 Jegantha, the Wellspring', resolvingAllCards());
		const sideboardOnly = await importBroadcastDeckList('Sideboard\n2 Duress', resolvingAllCards());

		expect(empty).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'EMPTY_DECK_LIST' })],
		});
		expect(companionOnly).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'EMPTY_DECK_LIST' })],
		});
		expect(sideboardOnly).toEqual({
			ok: true,
			document: expect.objectContaining({
				mainboard: [],
				sideboard: [expect.objectContaining({ canonicalName: 'Duress', quantity: 2 })],
			}),
		});
	});

	it('reports every unresolved row and distinguishes invalid printing hints', async () => {
		const resolver: BroadcastDeckListCardResolver = {
			resolve: vi.fn(async requests => requests.map(() => ({ status: 'unresolved' as const }))),
		};

		const result = await importBroadcastDeckList([
			'1 Missing Card',
			'1 Wrong Set (BAD)',
			'1 Wrong Collector (SLD) 9999',
		].join('\n'), resolver);

		expect(result).toEqual({
			ok: false,
			errors: [
				expect.objectContaining({ lineNumber: 1, code: 'UNRESOLVED_CARD', sourceText: '1 Missing Card' }),
				expect.objectContaining({ lineNumber: 2, code: 'INVALID_PRINTING_HINT', sourceText: '1 Wrong Set (BAD)' }),
				expect.objectContaining({ lineNumber: 3, code: 'INVALID_PRINTING_HINT', sourceText: '1 Wrong Collector (SLD) 9999' }),
			],
		});
	});

	it('continues resolving valid rows so one response contains every detectable bounded error', async () => {
		const resolver: BroadcastDeckListCardResolver = {
			resolve: vi.fn(async () => [{ status: 'unresolved' as const }]),
		};

		const result = await importBroadcastDeckList('not a card row\n1 Missing Card', resolver);

		expect(result).toEqual({
			ok: false,
			errors: [
				expect.objectContaining({ lineNumber: 1, code: 'INVALID_CARD_LINE' }),
				expect.objectContaining({ lineNumber: 2, code: 'UNRESOLVED_CARD' }),
			],
		});
	});

	it('orders line errors by physical source line regardless of detection phase', async () => {
		const resolver: BroadcastDeckListCardResolver = {
			resolve: vi.fn(async () => [{ status: 'unresolved' as const }]),
		};

		const result = await importBroadcastDeckList('1 Missing Card\nnot a card row', resolver);

		expect(result.ok).toBe(false);
		if (result.ok)
			return;
		expect(result.errors.map(error => 'lineNumber' in error ? error.lineNumber : null)).toEqual([1, 2]);
	});

	it('merges only the same resolved printing in one compartment and preserves first-occurrence order', async () => {
		const result = await importBroadcastDeckList([
			'2 Lightning Bolt (SLD) 1',
			'3 Shock',
			'4 Lightning Bolt (SLD) 1',
			'1 Lightning Bolt (SLD) 2',
			'Sideboard',
			'2 Lightning Bolt (SLD) 1',
		].join('\n'), resolvingAllCards());

		expect(result.ok).toBe(true);
		if (!result.ok)
			return;
		expect(result.document.mainboard.map(entry => ({
			id: entry.scryfallId,
			quantity: entry.quantity,
			sortOrder: entry.sortOrder,
		}))).toEqual([
			{ id: 'Lightning Bolt-sld-1', quantity: 6, sortOrder: 0 },
			{ id: 'Shock-default-default', quantity: 3, sortOrder: 1 },
			{ id: 'Lightning Bolt-sld-2', quantity: 1, sortOrder: 2 },
		]);
		expect(result.document.sideboard).toEqual([
			expect.objectContaining({ scryfallId: 'Lightning Bolt-sld-1', quantity: 2, sortOrder: 0 }),
		]);
	});

	it('refuses a merged entry whose quantity exceeds 999', async () => {
		const result = await importBroadcastDeckList(
			'600 Lightning Bolt (SLD) 1\n400 Lightning Bolt (SLD) 1',
			resolvingAllCards(),
		);

		expect(result).toEqual({
			ok: false,
			errors: [expect.objectContaining({ code: 'MERGED_QUANTITY_EXCEEDED' })],
		});
	});
});
