import type {
	BroadcastGraphicConfig,
	GraphicFill,
	GraphicSurfaceStyle,
} from '../../shared/types/graphics';
import type { GraphicAssetReference } from '../../shared/types/graphicsAsset';
import {
	addGraphicGroupChild,
	addGraphicItem,
} from '../../shared/modules/graphics';

/**
 * A Broadcast Graphic with every optional field of the vocabulary populated.
 *
 * It exists for round-trip assertions across a Template Package. A copy built by
 * naming the fields to keep silently drops every field added to the vocabulary
 * afterwards, and across an installation boundary the loss is invisible: a dropped
 * field is indistinguishable from one the *sending* installation legitimately did
 * not have, which is exactly what a version-pinned envelope is designed to tolerate.
 * Nothing in the received bytes says anything is missing.
 *
 * So the guard is a document with nothing absent, round-tripped and compared whole.
 * It fails the moment the vocabulary grows a field the export or import path does
 * not carry, rather than when somebody remembers to update a test — and it fails at
 * authoring time rather than after packages are already in the wild, where
 * re-exporting repairs nothing.
 *
 * Built through the same authoring operations an editor uses, so its base items can
 * never drift from what the editor actually produces.
 *
 * ## It is hand-enumerated, and that is the weakness it cannot fix
 *
 * The fixture guards against copies that enumerate the vocabulary, and it is itself
 * one. Deriving it from `broadcastGraphicConfigSchema` was the intent and does not
 * work: a maximal instance would have to be generated by walking Zod internals,
 * which cannot satisfy the cross-field refinements this document is only valid
 * under — Graphic Item ids unique across a Graphic Group's children, staggers naming
 * items that exist, a derived Graphic Source Selection following a relationship that
 * actually yields its declared kind, a binding naming a real catalog field. A
 * generator producing those is a seam of its own, and a wrong one would weaken the
 * guard rather than sharpen it.
 *
 * What holds it honest instead is that the round-trip compares whole documents. A
 * field added to the vocabulary and left out of here is invisible; a field added
 * here and dropped in transit is not. So the fixture is only as good as the next
 * author extending it — which is why every optional field is listed below in the
 * order the type declares it.
 */

const CANVAS = { canvasWidth: 1920, canvasHeight: 1080 };

/** The `linear-gradient` half of `GraphicFill`; the `solid` half is every default. */
const GRADIENT_FILL: GraphicFill = {
	type: 'linear-gradient',
	angle: 135,
	stops: [
		{ color: '#0077a3', position: 0, opacity: 1 },
		{ color: '#00394f', position: 0.5, opacity: 0.8 },
		{ color: '#000000', position: 1, opacity: 0.4 },
	],
};

/** Both optional halves of a Graphic Surface Style, over a gradient Graphic Fill. */
function maximalSurfaceStyle(): GraphicSurfaceStyle {
	return {
		fill: structuredClone(GRADIENT_FILL),
		fillOpacity: 0.9,
		outline: { color: '#ffffff', width: 3 },
		glow: { color: '#00d9ff', size: 18, opacity: 0.6 },
	};
}

export interface MaximalBroadcastGraphicOptions {
	id?: string;
	name?: string;
	/** The exact revision the Media Graphic Item pins. */
	asset: GraphicAssetReference;
}

export function maximalBroadcastGraphicDocument(
	options: MaximalBroadcastGraphicOptions,
): BroadcastGraphicConfig {
	const base: BroadcastGraphicConfig = {
		id: options.id ?? 'lower-third',
		name: options.name ?? 'Lower third',
		items: [],
	};
	const withGroup = addGraphicItem(base, { kind: 'group', id: 'cluster', ...CANVAS }).graphic;
	const withChild = addGraphicGroupChild(withGroup, { kind: 'shape', groupId: 'cluster', id: 'child' }).graphic;
	const withHeadline = addGraphicItem(withChild, { kind: 'text', id: 'headline', ...CANVAS }).graphic;
	const document = addGraphicItem(withHeadline, { kind: 'media', id: 'backdrop', ...CANVAS }).graphic;

	const group = document.items.find(item => item.id === 'cluster');
	if (group?.type !== 'group')
		throw new Error('expected a Graphic Group');
	const child = group.children[0];
	if (child?.type !== 'shape')
		throw new Error('expected a Shape Graphic Item inside the Graphic Group');
	const headline = document.items.find(item => item.id === 'headline');
	if (headline?.type !== 'text')
		throw new Error('expected a Text Graphic Item');
	const backdrop = document.items.find(item => item.id === 'backdrop');
	if (backdrop?.type !== 'media')
		throw new Error('expected a Media Graphic Item');

	// The one field a Template Package is *defined* to rewrite, so the round trip has
	// something to prove it rewrote as well as something to prove it carried.
	backdrop.asset = { ...options.asset };
	backdrop.clipGeometry = {
		topLeft: { treatment: 'rounded', size: 12 },
		topRight: { treatment: 'cut', size: 8 },
		bottomRight: { treatment: 'square', size: 0 },
		bottomLeft: { treatment: 'rounded', size: 4 },
		leftSlant: 6,
		rightSlant: 0,
	};
	backdrop.videoCompatibility = 'all-supported';
	backdrop.rotation = 3;
	backdrop.opacity = 0.85;
	backdrop.playbackRate = 1.25;
	backdrop.loop = false;

	headline.text = 'Match point for {headline}';
	// Every key a Graphic Placeholder Style may carry, not a representative few.
	headline.placeholderStyles = {
		headline: {
			fontId: 'inter',
			fontSize: 72,
			fontWeight: 900,
			fontStyle: 'italic',
			textTransform: 'uppercase',
			letterSpacing: 2,
			color: '#ffcc00',
		},
	};
	headline.surfaceStyle = maximalSurfaceStyle();
	headline.rotation = -2;

	// Main-axis sizing exists only on a Graphic Group child, so it can only be
	// covered here.
	child.sizing = { mode: 'fill', size: 240, weight: 2 };
	child.surfaceStyle = maximalSurfaceStyle();

	group.surfaceStyle = maximalSurfaceStyle();
	group.defaultChildSurfaceStyle = {
		fill: { type: 'solid', color: '#101820' },
		fillOpacity: 0.75,
		outline: { color: '#334155', width: 1 },
		glow: { color: '#000000', size: 4, opacity: 0.3 },
	};

	document.animation = {
		'enter': { duration: 400, easing: 'ease-out', delay: 100, fade: { opacity: 0 } },
		'on-screen': {
			duration: 800,
			easing: 'linear',
			delay: 0,
			pause: 200,
			repeat: 3,
			scale: { factor: 1.1, origin: 'center' },
		},
		'update': { duration: 250, easing: 'ease-in-out', delay: 0, fade: { opacity: 0.5 } },
		'exit': {
			duration: 300,
			easing: 'ease-in',
			delay: 0,
			slide: { direction: 'south', distanceMode: 'fixed', distance: 200 },
			reveal: { edge: 'left' },
		},
		'stagger': {
			'enter': { order: 'list', step: 80, itemIds: ['headline', 'cluster'] },
			'on-screen': { order: 'reverse-list', step: 40, itemIds: ['cluster'] },
			'update': { order: 'list', step: 20, itemIds: ['headline'] },
			'exit': { order: 'reverse-list', step: 60, itemIds: ['cluster', 'backdrop'] },
		},
	};
	group.animation = {
		enter: { duration: 300, easing: 'linear', delay: 0, fade: { opacity: 0 } },
		stagger: { enter: { order: 'list', step: 30, itemIds: ['child'] } },
	};
	headline.animation = {
		exit: { duration: 150, easing: 'ease-in', delay: 50, fade: { opacity: 0 } },
	};
	// All six Graphic Input types, because each is a separate branch of the wire
	// vocabulary and a package carrying five of them proves nothing about the sixth.
	document.inputs = [
		{
			type: 'text',
			key: 'headline',
			label: 'Headline',
			required: true,
			updatePolicy: 'staged',
			default: 'Match point',
			maxLength: 60,
		},
		{
			type: 'number',
			key: 'lifeTotal',
			label: 'Life total',
			required: false,
			updatePolicy: 'live',
			default: 20,
			min: 0,
			max: 99,
			integer: true,
		},
		{
			type: 'toggle',
			key: 'showTimer',
			label: 'Show timer',
			required: false,
			updatePolicy: 'live',
			default: true,
		},
		{
			type: 'choice',
			key: 'corner',
			label: 'Corner',
			required: false,
			updatePolicy: 'live',
			default: 'left',
			options: [{ value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }],
		},
		{
			type: 'color',
			key: 'accent',
			label: 'Accent',
			required: false,
			updatePolicy: 'staged',
			default: '#ff0055',
		},
		{
			type: 'media',
			key: 'sponsorLogo',
			label: 'Sponsor logo',
			required: false,
			updatePolicy: 'staged',
			// The same revision the Media Graphic Item pins, deliberately. Export
			// discovers packaged assets through the Screen reference index, which walks
			// Media Graphic Items and not Graphic Input defaults, so a *different*
			// revision here is refused at export as an undeclared reference. Naming one
			// the document already packages keeps this fixture about the round trip
			// rather than about that gap.
			default: { ...options.asset },
			mediaKind: 'image',
		},
	];
	// One operator-picked Graphic Source Selection and one derived from it, so the
	// optional `from` is covered by a relationship that really does yield `player`.
	document.sources = [
		{ key: 'match', label: 'Match', kind: 'match' },
		{ key: 'player', label: 'Player', kind: 'player', from: { sourceKey: 'match', relation: 'player1' } },
	];
	document.bindings = [{ inputKey: 'headline', sourceKey: 'player', fieldId: 'player.name' }];

	return document;
}
